export const AUTH = "AUTH";
/* CUSTOMIZER */
export const ADD_COSTOMIZER ="ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS ="ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIX_BACKGROUND_LAYOUT = "ADD_MIX_BACKGROUND_LAYOUT";
export const ROUTER_ANIMATION = "ROUTER_ANIMATION";
export const LISTING_INFORMATION = "LISTING_INFORMATION";
export const SOFTWARE_LISTING_FOR_SALE = "SOFTWARE_LISTING_FOR_SALE";
export const CHANGE_MAIN_STYLES = "CHANGE_MAIN_STYLES";
export const SAVE_APPLICATION_DETAILS = "SAVE_APPLICATION_DETAILS";